-- Script de inserción de datos para la tabla investor (PostgreSQL/Supabase)

INSERT INTO investor (id, name, created_at, created_by, updated_at, updated_by) VALUES 
(1, 'Bill Gates', NOW(), null, NOW(), null),
(2, 'Paul Allen', NOW(), null, NOW(), null),
(3, 'Halsey Minor', NOW(), null, NOW(), null),
(4, 'Larry Ellison', NOW(), null, NOW(), null),
(5, 'Hambrecht & Quist', NOW(), null, NOW(), null),
(6, 'Bob Miner', NOW(), null, NOW(), null),
(7, 'Dietmar Hopp', NOW(), null, NOW(), null),
(8, 'Klaus Tschira', NOW(), null, NOW(), null),
(9, 'Sierra Ventures', NOW(), null, NOW(), null),
(10, 'Kleiner Perkins', NOW(), null, NOW(), null),
(11, 'JMI Equity', NOW(), null, NOW(), null),
(12, 'Sequoia Capital', NOW(), null, NOW(), null),
(13, 'Greylock Partners', NOW(), null, NOW(), null),
(14, 'NEA', NOW(), null, NOW(), null),
(15, 'Emergence', NOW(), null, NOW(), null),
(16, 'Bessemer', NOW(), null, NOW(), null),
(17, 'FirstMark', NOW(), null, NOW(), null),
(18, 'Felicis', NOW(), null, NOW(), null),
(19, 'Accel Partners', NOW(), null, NOW(), null),
(20, 'Sequoia', NOW(), null, NOW(), null),
(21, 'ICONIQ', NOW(), null, NOW(), null),
(22, 'Altimeter', NOW(), null, NOW(), null),
(23, 'General Catalyst', NOW(), null, NOW(), null),
(24, 'Google Ventures', NOW(), null, NOW(), null),
(25, 'Accel', NOW(), null, NOW(), null),
(26, 'Andreessen Horowitz', NOW(), null, NOW(), null),
(27, 'Index Ventures', NOW(), null, NOW(), null),
(28, 'USV', NOW(), null, NOW(), null),
(29, 'Greylock', NOW(), null, NOW(), null),
(30, 'Union Square', NOW(), null, NOW(), null),
(31, 'Khosla Ventures', NOW(), null, NOW(), null),
(32, 'Founders Fund', NOW(), null, NOW(), null),
(33, 'In-Q-Tel', NOW(), null, NOW(), null),
(34, 'Bond', NOW(), null, NOW(), null),
(35, 'Sapphire Ventures', NOW(), null, NOW(), null),
(36, 'Insight', NOW(), null, NOW(), null),
(37, 'Benchmark', NOW(), null, NOW(), null),
(38, 'Thrive Capital', NOW(), null, NOW(), null),
(39, 'Goldman Sachs', NOW(), null, NOW(), null),
(40, 'Matrix Partners', NOW(), null, NOW(), null),
(41, 'DFJ', NOW(), null, NOW(), null),
(42, 'Index', NOW(), null, NOW(), null),
(43, 'Sequoia Capital India', NOW(), null, NOW(), null),
(44, 'Summit Partners', NOW(), null, NOW(), null),
(45, 'IVP', NOW(), null, NOW(), null),
(46, 'GV', NOW(), null, NOW(), null),
(47, 'Mayfield', NOW(), null, NOW(), null),
(48, 'Trinity', NOW(), null, NOW(), null),
(49, 'Tenaya', NOW(), null, NOW(), null),
(50, 'August Capital', NOW(), null, NOW(), null),
(51, 'JK&B Capital', NOW(), null, NOW(), null),
(52, 'Venrock', NOW(), null, NOW(), null),
(53, 'Foundry Group', NOW(), null, NOW(), null),
(54, 'Bootstrapped', NOW(), null, NOW(), null),
(55, 'OpenView', NOW(), null, NOW(), null),
(56, 'Sapphire', NOW(), null, NOW(), null),
(57, 'CapitalG', NOW(), null, NOW(), null),
(58, 'Battery', NOW(), null, NOW(), null),
(59, 'TPG', NOW(), null, NOW(), null),
(60, 'Lightspeed', NOW(), null, NOW(), null),
(61, 'Warburg Pincus', NOW(), null, NOW(), null),
(62, 'Khosla', NOW(), null, NOW(), null),
(63, 'Scale', NOW(), null, NOW(), null),
(64, 'Adams Street', NOW(), null, NOW(), null),
(65, 'Partech', NOW(), null, NOW(), null),
(66, 'Emergence Capital', NOW(), null, NOW(), null),
(67, 'Crosslink', NOW(), null, NOW(), null),
(68, 'Bank of America', NOW(), null, NOW(), null),
(69, 'TA Associates', NOW(), null, NOW(), null),
(70, 'Carlyle', NOW(), null, NOW(), null),
(71, 'Insight Partners', NOW(), null, NOW(), null),
(72, 'Madrona', NOW(), null, NOW(), null),
(73, 'TCV', NOW(), null, NOW(), null),
(74, 'Tiger Global', NOW(), null, NOW(), null),
(75, 'Coatue', NOW(), null, NOW(), null),
(76, 'Thrive', NOW(), null, NOW(), null),
(77, 'Lone Pine', NOW(), null, NOW(), null),
(78, 'Meritech', NOW(), null, NOW(), null),
(79, 'Spark', NOW(), null, NOW(), null),
(80, 'HarbourVest', NOW(), null, NOW(), null),
(81, 'Spark Capital', NOW(), null, NOW(), null),
(82, 'Redpoint', NOW(), null, NOW(), null),
(83, 'Greenoaks', NOW(), null, NOW(), null),
(84, 'DST Global', NOW(), null, NOW(), null),
(85, 'Ribbit Capital', NOW(), null, NOW(), null),
(86, 'Addition', NOW(), null, NOW(), null),
(87, 'Lux Capital', NOW(), null, NOW(), null),
(88, 'Arena Holdings', NOW(), null, NOW(), null),
(89, 'Durable Capital', NOW(), null, NOW(), null),
(90, 'Softbank', NOW(), null, NOW(), null),
(91, 'Salesforce Ventures', NOW(), null, NOW(), null),
(92, 'Tiger', NOW(), null, NOW(), null),
(93, 'Qumra', NOW(), null, NOW(), null),
(94, 'Generation IM', NOW(), null, NOW(), null),
(95, 'DFJ Growth', NOW(), null, NOW(), null),
(96, 'IAC', NOW(), null, NOW(), null);

-- Actualizar la secuencia para que continúe desde el último ID insertado
SELECT setval('investor_id_seq', (SELECT MAX(id) FROM investor));